# Generated by scripts/generate_models.py. Do not edit.

from __future__ import annotations

from typing import Any
from pydantic import Field, RootModel, constr
from local_bigquery.resource import Resource


class Discovery(RootModel[Any]):
    root: Any


class ModelExtractOptions(Resource):
    trialId: constr(pattern=r"^-?[0-9]+$") | None = None


class SerDeInfo(Resource):
    serializationLibrary: str | None = None
    name: str | None = None
    parameters: dict[str, str | None] | None = None


class StoredColumnsUnusedReason(Resource):
    message: str | None = None
    code: str | None = None
    uncoveredColumns: list[str] | None = None


class HivePartitioningOptions(Resource):
    sourceUriPrefix: str | None = None
    fields: list[str] | None = None
    mode: str | None = None
    requirePartitionFilter: bool | None = None


class PythonOptions(Resource):
    entryPoint: str | None = None
    packages: list[str] | None = None


class DatasetReference(Resource):
    datasetId: str | None = None
    projectId: str | None = None


class ModelReference(Resource):
    modelId: str | None = None
    projectId: str | None = None
    datasetId: str | None = None


class SessionInfo(Resource):
    sessionId: str | None = None


class ForeignViewDefinition(Resource):
    dialect: str | None = None
    query: str | None = None


class BinaryConfusionMatrix(Resource):
    accuracy: float | None = None
    truePositives: constr(pattern=r"^-?[0-9]+$") | None = None
    falseNegatives: constr(pattern=r"^-?[0-9]+$") | None = None
    recall: float | None = None
    trueNegatives: constr(pattern=r"^-?[0-9]+$") | None = None
    f1Score: float | None = None
    falsePositives: constr(pattern=r"^-?[0-9]+$") | None = None
    positiveClassThreshold: float | None = None
    precision: float | None = None


class ArrowSchema(Resource):
    serializedSchema: str | None = None


class InputDataChange(Resource):
    recordsReadDiffPercentage: float | None = None


class JobReference(Resource):
    projectId: str | None = None
    jobId: str | None = None
    location: str | None = None


class ExternalDatasetReference(Resource):
    connection: str | None = None
    externalSource: str | None = None


class JobStatisticsReservationUsageItem(Resource):
    slotMs: constr(pattern=r"^-?[0-9]+$") | None = None
    name: str | None = None


class SparkOptions(Resource):
    fileUris: list[str] | None = None
    pyFileUris: list[str] | None = None
    mainFileUri: str | None = None
    archiveUris: list[str] | None = None
    containerImage: str | None = None
    jarUris: list[str] | None = None
    runtimeVersion: str | None = None
    mainClass: str | None = None
    connection: str | None = None
    properties: dict[str, str | None] | None = None


class QueryInfo(Resource):
    optimizationDetails: dict[str, Any] | None = None


class DatasetTagsItem(Resource):
    tagKey: str | None = None
    tagValue: str | None = None


class QueryTimelineSample(Resource):
    shuffleRamUsageRatio: float | None = None
    completedUnits: constr(pattern=r"^-?[0-9]+$") | None = None
    activeUnits: constr(pattern=r"^-?[0-9]+$") | None = None
    elapsedMs: constr(pattern=r"^-?[0-9]+$") | None = None
    estimatedRunnableUnits: constr(pattern=r"^-?[0-9]+$") | None = None
    pendingUnits: constr(pattern=r"^-?[0-9]+$") | None = None
    totalSlotMs: constr(pattern=r"^-?[0-9]+$") | None = None


class DataMaskingStatistics(Resource):
    dataMaskingApplied: bool | None = None


class ScriptOptions(Resource):
    keyResultStatement: str | None = None
    statementTimeoutMs: constr(pattern=r"^-?[0-9]+$") | None = None
    statementByteBudget: constr(pattern=r"^-?[0-9]+$") | None = None


class MetadataCacheStalenessInsight(Resource):
    avgPreviousStalenessMs: str | None = None
    stalenessPercentageIncrease: float | None = None


class ExplainQueryStep(Resource):
    kind: str | None = None
    substeps: list[str] | None = None


class ExportDataStatistics(Resource):
    rowCount: constr(pattern=r"^-?[0-9]+$") | None = None
    fileCount: constr(pattern=r"^-?[0-9]+$") | None = None


class PruningStats(Resource):
    postCmetaPruningParallelInputCount: constr(pattern=r"^-?[0-9]+$") | None = None
    postCmetaPruningPartitionCount: constr(pattern=r"^-?[0-9]+$") | None = None
    preCmetaPruningParallelInputCount: constr(pattern=r"^-?[0-9]+$") | None = None


class DataPolicyOption(Resource):
    name: str | None = None


class GenAiFunctionCostOptimizationStats(Resource):
    numCostOptimizedRows: constr(pattern=r"^-?[0-9]+$") | None = None
    message: str | None = None


class DestinationTableProperties(Resource):
    expirationTime: str | None = None
    description: str | None = None
    friendlyName: str | None = None
    labels: dict[str, str | None] | None = None


class RoutineReference(Resource):
    routineId: str | None = None
    datasetId: str | None = None
    projectId: str | None = None


class JsonValue(RootModel[Any]):
    root: Any


class Expr(Resource):
    expression: str | None = None
    title: str | None = None
    description: str | None = None
    location: str | None = None


class IntArray(Resource):
    elements: list[constr(pattern=r"^-?[0-9]+$")] | None = None


class ObjectStorageStats(Resource):
    cloudProvider: str | None = None
    objectStorageBytesRead: constr(pattern=r"^-?[0-9]+$") | None = None
    cacheBytesRead: constr(pattern=r"^-?[0-9]+$") | None = None


class JsonOptions(Resource):
    encoding: str | None = None


class RankingMetrics(Resource):
    averageRank: float | None = None
    meanSquaredError: float | None = None
    meanAveragePrecision: float | None = None
    normalizedDiscountedCumulativeGain: float | None = None


class TransactionInfo(Resource):
    transactionId: str | None = None


class IntArrayHparamSearchSpace(Resource):
    candidates: list[IntArray] | None = None


class RegressionMetrics(Resource):
    meanSquaredLogError: float | None = None
    meanSquaredError: float | None = None
    meanAbsoluteError: float | None = None
    medianAbsoluteError: float | None = None
    rSquared: float | None = None


class DatasetAccessEntry(Resource):
    dataset: DatasetReference | None = None
    targetTypes: list[str] | None = None


class ProjectReference(Resource):
    projectId: str | None = None


class SparkLoggingInfo(Resource):
    projectId: str | None = None
    resourceType: str | None = None


class JobStatistics5(Resource):
    copiedLogicalBytes: constr(pattern=r"^-?[0-9]+$") | None = None
    copiedRows: constr(pattern=r"^-?[0-9]+$") | None = None
    remoteDestinationRegion: str | None = None


class GoogleSheetsOptions(Resource):
    range: str | None = None
    skipLeadingRows: constr(pattern=r"^-?[0-9]+$") | None = None


class Binding(Resource):
    condition: Expr | None = None
    role: str | None = None
    members: list[str] | None = None


class IntRange(Resource):
    min: constr(pattern=r"^-?[0-9]+$") | None = None
    max: constr(pattern=r"^-?[0-9]+$") | None = None


class GenAiFunctionCacheStats(Resource):
    numCacheHitRows: constr(pattern=r"^-?[0-9]+$") | None = None


class DatasetListDatasetsItem(Resource):
    externalDatasetReference: ExternalDatasetReference | None = None
    catalogSource: str | None = None
    id: str | None = None
    labels: dict[str, str | None] | None = None
    location: str | None = None
    datasetReference: DatasetReference | None = None
    friendlyName: str | None = None
    kind: str | None = None
    type: str | None = None


class DatasetList(Resource):
    kind: str | None = "bigquery#datasetList"
    etag: str | None = None
    nextPageToken: str | None = None
    unreachable: list[str] | None = None
    datasets: list[DatasetListDatasetsItem] | None = None


class ClusterInfo(Resource):
    clusterRadius: float | None = None
    clusterSize: constr(pattern=r"^-?[0-9]+$") | None = None
    centroidId: constr(pattern=r"^-?[0-9]+$") | None = None


class RowLevelSecurityStatistics(Resource):
    rowLevelSecurityApplied: bool | None = None


class TestIamPermissionsResponse(Resource):
    permissions: list[str] | None = None


class MaterializedViewDefinition(Resource):
    allowNonIncrementalDefinition: bool | None = None
    enableRefresh: bool | None = None
    lastRefreshTime: constr(pattern=r"^-?[0-9]+$") | None = None
    query: str | None = None
    refreshIntervalMs: constr(pattern=r"^-?[0-9]+$") | None = None
    maxStaleness: str | None = None


class LocationMetadata(Resource):
    legacyLocationId: str | None = None


class Streamingbuffer(Resource):
    estimatedBytes: constr(pattern=r"^[0-9]+$") | None = None
    estimatedRows: constr(pattern=r"^[0-9]+$") | None = None
    oldestEntryTime: constr(pattern=r"^[0-9]+$") | None = None


class ForeignTypeInfo(Resource):
    typeSystem: str | None = None


class DmlStatistics(Resource):
    deletedRowCount: constr(pattern=r"^-?[0-9]+$") | None = None
    updatedRowCount: constr(pattern=r"^-?[0-9]+$") | None = None
    fineGrainedDmlUnusedReason: str | None = None
    insertedRowCount: constr(pattern=r"^-?[0-9]+$") | None = None
    dmlMode: str | None = None


class EncryptionConfiguration(Resource):
    kmsKeyName: str | None = None


class IncrementalResultStats(Resource):
    resultSetLastReplaceTime: str | None = None
    resultSetLastModifyTime: str | None = None
    disabledReason: str | None = None
    disabledReasonDetails: str | None = None
    lastIncrementalRowTime: str | None = None
    firstIncrementalRowTime: str | None = None
    incrementalRowCount: constr(pattern=r"^-?[0-9]+$") | None = None


class JoinRestrictionPolicy(Resource):
    joinAllowedColumns: list[str] | None = None
    joinCondition: str | None = None


class StringHparamSearchSpace(Resource):
    candidates: list[str] | None = None


class DataFormatOptions(Resource):
    useInt64Timestamp: bool | None = None
    timestampOutputFormat: str | None = None


class StorageDescriptor(Resource):
    outputFormat: str | None = None
    serdeInfo: SerDeInfo | None = None
    inputFormat: str | None = None
    locationUri: str | None = None


class IntCandidates(Resource):
    candidates: list[constr(pattern=r"^-?[0-9]+$")] | None = None


class DoubleCandidates(Resource):
    candidates: list[float] | None = None


class ScriptStackFrame(Resource):
    endLine: int | None = None
    procedureId: str | None = None
    text: str | None = None
    startColumn: int | None = None
    endColumn: int | None = None
    startLine: int | None = None


class TimePartitioning(Resource):
    expirationMs: constr(pattern=r"^-?[0-9]+$") | None = None
    requirePartitionFilter: bool | None = Field(None, deprecated=True)
    field: str | None = None
    type: str | None = None


class JobCreationReason(Resource):
    code: str | None = None


class RestrictionConfig(Resource):
    type: str | None = None


class LinkedDatasetSource(Resource):
    sourceDataset: DatasetReference | None = None


class ParquetOptions(Resource):
    enableListInference: bool | None = None
    mapTargetType: str | None = None
    enumAsString: bool | None = None


class TableFieldSchemaRangeElementType(Resource):
    type: str | None = None


class TableFieldSchemaPolicyTags(Resource):
    names: list[str] | None = None


class TableFieldSchemaDataGovernanceTagsInfo(Resource):
    dataGovernanceTags: dict[str, str | None] | None = None


class TableFieldSchemaCategories(Resource):
    names: list[str] | None = None


class ProjectListProjectsItem(Resource):
    projectReference: ProjectReference | None = None
    id: str | None = None
    numericId: constr(pattern=r"^[0-9]+$") | None = None
    friendlyName: str | None = None
    kind: str | None = None


class ProjectList(Resource):
    projects: list[ProjectListProjectsItem] | None = None
    totalItems: int | None = None
    kind: str | None = "bigquery#projectList"
    etag: str | None = None
    nextPageToken: str | None = None


class ModelDefinitionModelOptions(Resource):
    modelType: str | None = None
    labels: list[str] | None = None
    lossType: str | None = None


class DifferentialPrivacyPolicy(Resource):
    epsilonBudget: float | None = None
    maxEpsilonPerQuery: float | None = None
    maxGroupsContributed: constr(pattern=r"^-?[0-9]+$") | None = None
    privacyUnitColumn: str | None = None
    deltaBudgetRemaining: float | None = None
    deltaBudget: float | None = None
    deltaPerQuery: float | None = None
    epsilonBudgetRemaining: float | None = None


class BqmlIterationResult(Resource):
    index: int | None = None
    evalLoss: float | None = None
    learnRate: float | None = None
    trainingLoss: float | None = None
    durationMs: constr(pattern=r"^-?[0-9]+$") | None = None


class PropertyGraphReference(Resource):
    projectId: str | None = None
    datasetId: str | None = None
    propertyGraphId: str | None = None


class ArrowSerializationOptions(Resource):
    bufferCompression: str | None = None
    picosTimestampPrecision: str | None = None


class DimensionalityReductionMetrics(Resource):
    totalExplainedVarianceRatio: float | None = None


class BatchDeleteRowAccessPoliciesRequest(Resource):
    policyIds: list[str] | None = None
    force: bool | None = None


class UserDefinedFunctionResource(Resource):
    inlineCode: str | None = None
    resourceUri: str | None = None


class PrincipalComponentInfo(Resource):
    cumulativeExplainedVarianceRatio: float | None = None
    explainedVariance: float | None = None
    explainedVarianceRatio: float | None = None
    principalComponentId: constr(pattern=r"^-?[0-9]+$") | None = None


class BigtableProtoConfig(Resource):
    protoMessageName: str | None = None
    schemaBundleId: str | None = None


class RowAccessPolicyReference(Resource):
    datasetId: str | None = None
    tableId: str | None = None
    policyId: str | None = None
    projectId: str | None = None


class Entry(Resource):
    predictedLabel: str | None = None
    itemCount: constr(pattern=r"^-?[0-9]+$") | None = None


class ErrorProto(Resource):
    reason: str | None = None
    location: str | None = None
    message: str | None = None
    debugInfo: str | None = None


class CsvOptions(Resource):
    nullMarker: str | None = None
    skipLeadingRows: constr(pattern=r"^-?[0-9]+$") | None = None
    allowQuotedNewlines: bool | None = None
    encoding: str | None = None
    preserveAsciiControlCharacters: bool | None = None
    sourceColumnMatch: str | None = None
    allowJaggedRows: bool | None = None
    nullMarkers: list[str] | None = None
    fieldDelimiter: str | None = None
    quote: str | None = None


class ArrowRecordBatch(Resource):
    serializedRecordBatch: str | None = None


class JobStatus(Resource):
    errorResult: ErrorProto | None = None
    state: str | None = None
    errors: list[ErrorProto] | None = None


class UndeleteDatasetRequest(Resource):
    deletionTime: str | None = None


class GetServiceAccountResponse(Resource):
    email: str | None = None
    kind: str | None = "bigquery#getServiceAccountResponse"


class AvroOptions(Resource):
    useAvroLogicalTypes: bool | None = None


class BigLakeConfiguration(Resource):
    fileFormat: str | None = None
    connectionId: str | None = None
    storageUri: str | None = None
    tableFormat: str | None = None


class DoubleRange(Resource):
    max: float | None = None
    min: float | None = None


class ArimaCoefficients(Resource):
    autoRegressiveCoefficients: list[float] | None = None
    movingAverageCoefficients: list[float] | None = None
    interceptCoefficient: float | None = None


class Clustering(Resource):
    fields: list[str] | None = None


class GenAiFunctionErrorStats(Resource):
    errors: list[str] | None = None
    numFailedRows: constr(pattern=r"^-?[0-9]+$") | None = None


class TableConstraintsPrimaryKey(Resource):
    columns: list[str] | None = None


class TableConstraintsForeignKeysItemColumnReferencesItem(Resource):
    referencedColumn: str | None = None
    referencingColumn: str | None = None


class TableConstraintsForeignKeysItemReferencedTable(Resource):
    projectId: str | None = None
    datasetId: str | None = None
    tableId: str | None = None


class TableConstraintsForeignKeysItem(Resource):
    columnReferences: (
        list[TableConstraintsForeignKeysItemColumnReferencesItem] | None
    ) = None
    name: str | None = None
    referencedTable: TableConstraintsForeignKeysItemReferencedTable | None = Field(
        None, title="TableConstraintsForeignKeysItemReferencedTable"
    )


class TableConstraints(Resource):
    primaryKey: TableConstraintsPrimaryKey | None = Field(
        None, title="TableConstraintsPrimaryKey"
    )
    foreignKeys: list[TableConstraintsForeignKeysItem] | None = None


class SkewSource(Resource):
    stageId: constr(pattern=r"^-?[0-9]+$") | None = None
    outputBytesMedian: constr(pattern=r"^-?[0-9]+$") | None = None
    outputBytesP95: constr(pattern=r"^-?[0-9]+$") | None = None
    outputBytesMax: constr(pattern=r"^-?[0-9]+$") | None = None


class RemoteFunctionOptions(Resource):
    endpoint: str | None = None
    connection: str | None = None
    maxBatchingRows: constr(pattern=r"^-?[0-9]+$") | None = None
    userDefinedContext: dict[str, str | None] | None = None


class JobStatistics2ReservationUsageItem(Resource):
    slotMs: constr(pattern=r"^-?[0-9]+$") | None = None
    name: str | None = None


class JsonObject(RootModel[dict[str, JsonValue]]):
    root: dict[str, JsonValue]


class SparkStatistics(Resource):
    kmsKeyName: str | None = None
    sparkJobLocation: str | None = None
    sparkJobId: str | None = None
    endpoints: dict[str, str | None] | None = None
    loggingInfo: SparkLoggingInfo | None = None
    gcsStagingBucket: str | None = None


class TableCell(Resource):
    v: Any | None = None


class TestIamPermissionsRequest(Resource):
    permissions: list[str] | None = None


class ExternalCatalogDatasetOptions(Resource):
    defaultStorageLocationUri: str | None = None
    parameters: dict[str, str | None] | None = None


class BqmlTrainingRunTrainingOptions(Resource):
    lineSearchInitLearnRate: float | None = None
    l2Reg: float | None = None
    warmStart: bool | None = None
    earlyStop: bool | None = None
    learnRate: float | None = None
    l1Reg: float | None = None
    maxIteration: constr(pattern=r"^-?[0-9]+$") | None = None
    minRelProgress: float | None = None
    learnRateStrategy: str | None = None


class BqmlTrainingRun(Resource):
    trainingOptions: BqmlTrainingRunTrainingOptions | None = Field(
        None, title="BqmlTrainingRunTrainingOptions"
    )
    iterationResults: list[BqmlIterationResult] | None = None
    startTime: str | None = None
    state: str | None = None


class BiEngineReason(Resource):
    code: str | None = None
    message: str | None = None


class Explanation(Resource):
    attribution: float | None = None
    featureName: str | None = None


class GenAiErrorStats(Resource):
    errors: list[str] | None = None


class MaterializedViewStatus(Resource):
    lastRefreshStatus: ErrorProto | None = None
    refreshWatermark: str | None = None


class AggregationThresholdPolicy(Resource):
    privacyUnitColumns: list[str] | None = None
    threshold: constr(pattern=r"^-?[0-9]+$") | None = None


class GeneratedExpressionInfo(Resource):
    generationExpression: str | None = None
    stored: bool | None = None
    asynchronous: bool | None = None


class AuditLogConfig(Resource):
    exemptedMembers: list[str] | None = None
    logType: str | None = None


class AggregateClassificationMetrics(Resource):
    threshold: float | None = None
    accuracy: float | None = None
    f1Score: float | None = None
    logLoss: float | None = None
    precision: float | None = None
    rocAuc: float | None = None
    recall: float | None = None


class BigQueryModelTraining(Resource):
    expectedTotalIterations: constr(pattern=r"^-?[0-9]+$") | None = None
    currentIteration: int | None = None


class HighCardinalityJoin(Resource):
    leftRows: constr(pattern=r"^-?[0-9]+$") | None = None
    outputRows: constr(pattern=r"^-?[0-9]+$") | None = None
    rightRows: constr(pattern=r"^-?[0-9]+$") | None = None
    stepIndex: int | None = None


class ExternalCatalogTableOptions(Resource):
    storageDescriptor: StorageDescriptor | None = None
    connectionId: str | None = None
    parameters: dict[str, str | None] | None = None


class CategoryCount(Resource):
    category: str | None = None
    count: constr(pattern=r"^-?[0-9]+$") | None = None


class RemoteModelInfo(Resource):
    maxBatchingRows: constr(pattern=r"^-?[0-9]+$") | None = None
    endpoint: str | None = None
    remoteModelVersion: str | None = None
    speechRecognizer: str | None = None
    connection: str | None = None
    remoteServiceType: str | None = None


class ArimaOrder(Resource):
    p: constr(pattern=r"^-?[0-9]+$") | None = None
    q: constr(pattern=r"^-?[0-9]+$") | None = None
    d: constr(pattern=r"^-?[0-9]+$") | None = None


class JobStatistics3(Resource):
    inputFileBytes: constr(pattern=r"^-?[0-9]+$") | None = None
    inputFiles: constr(pattern=r"^-?[0-9]+$") | None = None
    outputBytes: constr(pattern=r"^-?[0-9]+$") | None = None
    outputRows: constr(pattern=r"^-?[0-9]+$") | None = None
    timeline: list[QueryTimelineSample] | None = None
    badRecords: constr(pattern=r"^-?[0-9]+$") | None = None


class PartitionedColumn(Resource):
    field: str | None = None


class RangePartitioningRange(Resource):
    end: constr(pattern=r"^-?[0-9]+$") | None = None
    interval: constr(pattern=r"^-?[0-9]+$") | None = None
    start: constr(pattern=r"^-?[0-9]+$") | None = None


class RangePartitioning(Resource):
    field: str | None = None
    range: RangePartitioningRange | None = Field(None, title="RangePartitioningRange")


class DataPolicyList(Resource):
    dataPolicies: list[DataPolicyOption] | None = None


class ArimaFittingMetrics(Resource):
    aic: float | None = None
    logLikelihood: float | None = None
    variance: float | None = None


class ExplainQueryStage(Resource):
    computeMsMax: constr(pattern=r"^-?[0-9]+$") | None = None
    readMsMax: constr(pattern=r"^-?[0-9]+$") | None = None
    endMs: constr(pattern=r"^-?[0-9]+$") | None = None
    shuffleOutputBytes: constr(pattern=r"^-?[0-9]+$") | None = None
    writeRatioAvg: float | None = None
    recordsWritten: constr(pattern=r"^-?[0-9]+$") | None = None
    recordsRead: constr(pattern=r"^-?[0-9]+$") | None = None
    status: str | None = None
    waitMsMax: constr(pattern=r"^-?[0-9]+$") | None = None
    shuffleOutputBytesSpilled: constr(pattern=r"^-?[0-9]+$") | None = None
    startMs: constr(pattern=r"^-?[0-9]+$") | None = None
    slotMs: constr(pattern=r"^-?[0-9]+$") | None = None
    writeRatioMax: float | None = None
    computeMsAvg: constr(pattern=r"^-?[0-9]+$") | None = None
    id: constr(pattern=r"^-?[0-9]+$") | None = None
    computeMode: str | None = None
    writeMsMax: constr(pattern=r"^-?[0-9]+$") | None = None
    readRatioAvg: float | None = None
    readRatioMax: float | None = None
    name: str | None = None
    computeRatioMax: float | None = None
    waitMsAvg: constr(pattern=r"^-?[0-9]+$") | None = None
    readMsAvg: constr(pattern=r"^-?[0-9]+$") | None = None
    waitRatioMax: float | None = None
    computeRatioAvg: float | None = None
    inputStages: list[constr(pattern=r"^-?[0-9]+$")] | None = None
    writeMsAvg: constr(pattern=r"^-?[0-9]+$") | None = None
    completedParallelInputs: constr(pattern=r"^-?[0-9]+$") | None = None
    parallelInputs: constr(pattern=r"^-?[0-9]+$") | None = None
    steps: list[ExplainQueryStep] | None = None
    waitRatioAvg: float | None = None


class ExternalRuntimeOptions(Resource):
    containerMemory: str | None = None
    containerCpu: float | None = None
    maxBatchingRows: constr(pattern=r"^-?[0-9]+$") | None = None
    runtimeVersion: str | None = None
    containerRequestConcurrency: constr(pattern=r"^-?[0-9]+$") | None = None
    runtimeConnection: str | None = None


class LoadQueryStatistics(Resource):
    outputBytes: constr(pattern=r"^-?[0-9]+$") | None = None
    outputRows: constr(pattern=r"^-?[0-9]+$") | None = None
    bytesTransferred: constr(pattern=r"^-?[0-9]+$") | None = Field(
        None, deprecated=True
    )
    inputFiles: constr(pattern=r"^-?[0-9]+$") | None = None
    badRecords: constr(pattern=r"^-?[0-9]+$") | None = None
    inputFileBytes: constr(pattern=r"^-?[0-9]+$") | None = None


class GetPolicyOptions(Resource):
    requestedPolicyVersion: int | None = None


class LinkedDatasetMetadata(Resource):
    linkState: str | None = None


class ConnectionProperty(Resource):
    key: str | None = None
    value: str | None = None


class ExternalServiceCost(Resource):
    billingMethod: str | None = None
    bytesProcessed: constr(pattern=r"^-?[0-9]+$") | None = None
    reservedSlotCount: constr(pattern=r"^-?[0-9]+$") | None = None
    bytesBilled: constr(pattern=r"^-?[0-9]+$") | None = None
    slotMs: constr(pattern=r"^-?[0-9]+$") | None = None
    externalService: str | None = None


class TableReference(Resource):
    datasetId: str | None = None
    tableId: str | None = None
    projectId: str | None = None


class JobStatistics4(Resource):
    destinationUriFileCounts: list[constr(pattern=r"^-?[0-9]+$")] | None = None
    inputBytes: constr(pattern=r"^-?[0-9]+$") | None = None
    timeline: list[QueryTimelineSample] | None = None


class StagePerformanceChangeInsight(Resource):
    inputDataChange: InputDataChange | None = None
    stageId: constr(pattern=r"^-?[0-9]+$") | None = None


class JobConfigurationTableCopy(Resource):
    sourceTable: TableReference | None = None
    destinationEncryptionConfiguration: EncryptionConfiguration | None = None
    writeDisposition: str | None = None
    operationType: str | None = None
    sourceTables: list[TableReference] | None = None
    destinationExpirationTime: str | None = None
    destinationTable: TableReference | None = None
    createDisposition: str | None = None


class TrainingOptions(Resource):
    maxTreeDepth: constr(pattern=r"^-?[0-9]+$") | None = None
    modelUri: str | None = None
    dimensionIdColumns: list[str] | None = None
    warmStart: bool | None = None
    vertexAiModelVersionAliases: list[str] | None = None
    hparamTuningObjectives: list[str] | None = None
    modelRegistry: str | None = None
    dataFrequency: str | None = None
    l2Regularization: float | None = None
    pcaSolver: str | None = None
    initialLearnRate: float | None = None
    autoClassWeights: bool | None = None
    holidayRegions: list[str] | None = None
    holidayRegion: str | None = None
    dropout: float | None = None
    minAprioriSupport: float | None = None
    dataSplitEvalFraction: float | None = None
    forecastLimitUpperBound: float | None = None
    hiddenUnits: list[constr(pattern=r"^-?[0-9]+$")] | None = None
    numFactors: constr(pattern=r"^-?[0-9]+$") | None = None
    dartNormalizeType: str | None = None
    standardizeFeatures: bool | None = None
    feedbackType: str | None = None
    itemColumn: str | None = None
    walsAlpha: float | None = None
    autoArimaMinOrder: constr(pattern=r"^-?[0-9]+$") | None = None
    minTreeChildWeight: constr(pattern=r"^-?[0-9]+$") | None = None
    activationFn: str | None = None
    tfVersion: str | None = None
    decomposeTimeSeries: bool | None = None
    forecastLimitLowerBound: float | None = None
    l1Regularization: float | None = None
    kmeansInitializationColumn: str | None = None
    categoryEncodingMethod: str | None = None
    batchSize: constr(pattern=r"^-?[0-9]+$") | None = None
    sampledShapleyNumPaths: constr(pattern=r"^-?[0-9]+$") | None = None
    colsampleBylevel: float | None = None
    minSplitLoss: float | None = None
    subsample: float | None = None
    integratedGradientsNumSteps: constr(pattern=r"^-?[0-9]+$") | None = None
    modelGardenModelName: str | None = None
    adjustStepChanges: bool | None = None
    maxReplicaCount: constr(pattern=r"^-?[0-9]+$") | None = None
    labelClassWeights: dict[str, float | None] | None = None
    minRelativeProgress: float | None = None
    dataSplitMethod: str | None = None
    timeSeriesLengthFraction: float | None = None
    timeSeriesDataColumn: str | None = None
    numPrincipalComponents: constr(pattern=r"^-?[0-9]+$") | None = None
    earlyStop: bool | None = None
    numTrials: constr(pattern=r"^-?[0-9]+$") | None = None
    reservationAffinityValues: list[str] | None = None
    timeSeriesIdColumns: list[str] | None = None
    autoArima: bool | None = None
    numClusters: constr(pattern=r"^-?[0-9]+$") | None = None
    calculatePValues: bool | None = None
    huggingFaceModelId: str | None = None
    cleanSpikesAndDips: bool | None = None
    optimizer: str | None = None
    distanceType: str | None = None
    numParallelTree: constr(pattern=r"^-?[0-9]+$") | None = None
    approxGlobalFeatureContrib: bool | None = None
    contributionMetric: str | None = None
    includeDrift: bool | None = None
    timeSeriesTimestampColumn: str | None = None
    colsampleBytree: float | None = None
    minTimeSeriesLength: constr(pattern=r"^-?[0-9]+$") | None = None
    maxParallelTrials: constr(pattern=r"^-?[0-9]+$") | None = None
    maxTimeSeriesLength: constr(pattern=r"^-?[0-9]+$") | None = None
    userColumn: str | None = None
    pcaExplainedVarianceRatio: float | None = None
    timeSeriesIdColumn: str | None = None
    fitIntercept: bool | None = None
    machineType: str | None = None
    endpointIdleTtl: str | None = None
    scaleFeatures: bool | None = None
    budgetHours: float | None = None
    enableGlobalExplain: bool | None = None
    learnRate: float | None = None
    dataSplitColumn: str | None = None
    horizon: constr(pattern=r"^-?[0-9]+$") | None = None
    reservationAffinityKey: str | None = None
    nonSeasonalOrder: ArimaOrder | None = None
    optimizationStrategy: str | None = None
    boosterType: str | None = None
    autoArimaMaxOrder: constr(pattern=r"^-?[0-9]+$") | None = None
    trendSmoothingWindowSize: constr(pattern=r"^-?[0-9]+$") | None = None
    colsampleBynode: float | None = None
    maxIterations: constr(pattern=r"^-?[0-9]+$") | None = None
    inputLabelColumns: list[str] | None = None
    treeMethod: str | None = None
    isTestColumn: str | None = None
    colorSpace: str | None = None
    instanceWeightColumn: str | None = None
    l1RegActivation: float | None = None
    reservationAffinityType: str | None = None
    kmeansInitializationMethod: str | None = None
    learnRateStrategy: str | None = None
    lossType: str | None = None
    xgboostVersion: str | None = None
    minReplicaCount: constr(pattern=r"^-?[0-9]+$") | None = None


class ScriptStatistics(Resource):
    evaluationKind: str | None = None
    stackFrames: list[ScriptStackFrame] | None = None


class TableMetadataCacheUsage(Resource):
    pruningStats: PruningStats | None = None
    unusedReason: str | None = None
    tableType: str | None = None
    explanation: str | None = None
    tableReference: TableReference | None = None
    staleness: str | None = None


class CloneDefinition(Resource):
    baseTableReference: TableReference | None = None
    cloneTime: str | None = None


class CategoricalValue(Resource):
    categoryCounts: list[CategoryCount] | None = None


class IntHparamSearchSpace(Resource):
    range: IntRange | None = None
    candidates: IntCandidates | None = None


class PartitionSkew(Resource):
    skewSources: list[SkewSource] | None = None


class DatasetAccessItem(Resource):
    iamMember: str | None = None
    userByEmail: str | None = None
    role: str | None = None
    routine: RoutineReference | None = None
    dataset: DatasetAccessEntry | None = None
    condition: Expr | None = None
    view: TableReference | None = None
    groupByEmail: str | None = None
    domain: str | None = None
    specialGroup: str | None = None


class Dataset(Resource):
    creationTime: constr(pattern=r"^-?[0-9]+$") | None = None
    restrictions: RestrictionConfig | None = None
    resourceTags: dict[str, str | None] | None = None
    etag: str | None = None
    datasetReference: DatasetReference | None = None
    maxTimeTravelHours: constr(pattern=r"^-?[0-9]+$") | None = None
    defaultRoundingMode: str | None = None
    description: str | None = None
    isCaseInsensitive: bool | None = None
    id: str | None = None
    defaultCollation: str | None = None
    externalDatasetReference: ExternalDatasetReference | None = None
    satisfiesPzs: bool | None = None
    type: str | None = None
    defaultPartitionExpirationMs: constr(pattern=r"^-?[0-9]+$") | None = None
    storageBillingModel: str | None = None
    tags: list[DatasetTagsItem] | None = Field(None, deprecated=True)
    access: list[DatasetAccessItem] | None = None
    selfLink: str | None = None
    catalogSource: str | None = None
    location: str | None = None
    satisfiesPzi: bool | None = None
    linkedDatasetMetadata: LinkedDatasetMetadata | None = None
    defaultTableExpirationMs: constr(pattern=r"^-?[0-9]+$") | None = None
    linkedDatasetSource: LinkedDatasetSource | None = None
    defaultEncryptionConfiguration: EncryptionConfiguration | None = None
    externalCatalogDatasetOptions: ExternalCatalogDatasetOptions | None = None
    labels: dict[str, str | None] | None = None
    kind: str | None = "bigquery#dataset"
    friendlyName: str | None = None
    lastModifiedTime: constr(pattern=r"^-?[0-9]+$") | None = None


class GenAiFunctionStats(Resource):
    errorStats: GenAiFunctionErrorStats | None = None
    prompt: str | None = None
    numProcessedRows: constr(pattern=r"^-?[0-9]+$") | None = None
    costOptimizationStats: GenAiFunctionCostOptimizationStats | None = None
    cacheStats: GenAiFunctionCacheStats | None = None
    functionName: str | None = None


class IndexUnusedReason(Resource):
    message: str | None = None
    baseTable: TableReference | None = None
    code: str | None = None
    indexName: str | None = None


class DoubleHparamSearchSpace(Resource):
    candidates: DoubleCandidates | None = None
    range: DoubleRange | None = None


class ArimaSingleModelForecastingMetrics(Resource):
    hasStepChanges: bool | None = None
    arimaFittingMetrics: ArimaFittingMetrics | None = None
    hasHolidayEffect: bool | None = None
    timeSeriesIds: list[str] | None = None
    hasDrift: bool | None = None
    seasonalPeriods: list[str] | None = None
    timeSeriesId: str | None = None
    hasSpikesAndDips: bool | None = None
    nonSeasonalOrder: ArimaOrder | None = None


class RowAccessPolicy(Resource):
    grantees: list[str] | None = None
    lastModifiedTime: str | None = None
    creationTime: str | None = None
    etag: str | None = None
    rowAccessPolicyReference: RowAccessPolicyReference | None = None
    filterPredicate: str | None = None


class TableDataInsertAllRequestRowsItem(Resource):
    json_: JsonObject | None = Field(None, alias="json")
    insertId: str | None = None


class TableDataInsertAllRequest(Resource):
    rows: list[TableDataInsertAllRequestRowsItem] | None = None
    ignoreUnknownValues: bool | None = None
    traceId: str | None = None
    templateSuffix: str | None = None
    kind: str | None = "bigquery#tableDataInsertAllRequest"
    skipInvalidRows: bool | None = None


class GlobalExplanation(Resource):
    classLabel: str | None = None
    explanations: list[Explanation] | None = None


class BiEngineStatistics(Resource):
    biEngineMode: str | None = None
    accelerationMode: str | None = None
    biEngineReasons: list[BiEngineReason] | None = None


class ArimaModelInfo(Resource):
    hasSpikesAndDips: bool | None = None
    timeSeriesId: str | None = None
    nonSeasonalOrder: ArimaOrder | None = None
    arimaCoefficients: ArimaCoefficients | None = None
    seasonalPeriods: list[str] | None = None
    arimaFittingMetrics: ArimaFittingMetrics | None = None
    hasHolidayEffect: bool | None = None
    timeSeriesIds: list[str] | None = None
    hasDrift: bool | None = None
    hasStepChanges: bool | None = None


class BinaryClassificationMetrics(Resource):
    binaryConfusionMatrixList: list[BinaryConfusionMatrix] | None = None
    aggregateClassificationMetrics: AggregateClassificationMetrics | None = None
    negativeLabel: str | None = None
    positiveLabel: str | None = None


class GeneratedColumn(Resource):
    generatedExpressionInfo: GeneratedExpressionInfo | None = None
    generatedMode: str | None = None


class DataSplitResult(Resource):
    trainingTable: TableReference | None = None
    evaluationTable: TableReference | None = None
    testTable: TableReference | None = None


class BigtableColumn(Resource):
    qualifierEncoded: str | None = None
    type: str | None = None
    encoding: str | None = None
    protoConfig: BigtableProtoConfig | None = None
    qualifierString: str | None = None
    onlyReadLatest: bool | None = None
    fieldName: str | None = None


class PrivacyPolicy(Resource):
    aggregationThresholdPolicy: AggregationThresholdPolicy | None = None
    differentialPrivacyPolicy: DifferentialPrivacyPolicy | None = None
    joinRestrictionPolicy: JoinRestrictionPolicy | None = None


class GenAiStats(Resource):
    errorStats: GenAiErrorStats | None = None
    functionStats: list[GenAiFunctionStats] | None = None


class JobConfigurationExtract(Resource):
    destinationUri: str | None = None
    destinationFormat: str | None = None
    fieldDelimiter: str | None = None
    modelExtractOptions: ModelExtractOptions | None = None
    destinationUris: list[str] | None = None
    sourceModel: ModelReference | None = None
    sourceTable: TableReference | None = None
    compression: str | None = None
    printHeader: bool | None = None
    useAvroLogicalTypes: bool | None = None


class MetadataCacheStatistics(Resource):
    tableMetadataCacheUsage: list[TableMetadataCacheUsage] | None = None


class TableFieldSchema(Resource):
    collation: str | None = None
    name: str | None = None
    dataPolicies: list[DataPolicyOption] | None = None
    roundingMode: str | None = None
    rangeElementType: TableFieldSchemaRangeElementType | None = Field(
        None, title="TableFieldSchemaRangeElementType"
    )
    scale: constr(pattern=r"^-?[0-9]+$") | None = None
    defaultValueExpression: str | None = None
    policyTags: TableFieldSchemaPolicyTags | None = Field(
        None, title="TableFieldSchemaPolicyTags"
    )
    precision: constr(pattern=r"^-?[0-9]+$") | None = None
    dataGovernanceTagsInfo: TableFieldSchemaDataGovernanceTagsInfo | None = Field(
        None, title="TableFieldSchemaDataGovernanceTagsInfo"
    )
    timestampPrecision: constr(pattern=r"^-?[0-9]+$") | None = None
    categories: TableFieldSchemaCategories | None = Field(
        None, title="TableFieldSchemaCategories"
    )
    description: str | None = None
    foreignTypeDefinition: str | None = None
    generatedColumn: GeneratedColumn | None = None
    dataPolicyList: DataPolicyList | None = None
    maxLength: constr(pattern=r"^-?[0-9]+$") | None = None
    mode: str | None = None
    fields: list[TableFieldSchema] | None = None
    type: str | None = None


class Row(Resource):
    actualLabel: str | None = None
    entries: list[Entry] | None = None


class ListRowAccessPoliciesResponse(Resource):
    nextPageToken: str | None = None
    rowAccessPolicies: list[RowAccessPolicy] | None = None


class ModelDefinition(Resource):
    modelOptions: ModelDefinitionModelOptions | None = Field(
        None, title="ModelDefinitionModelOptions"
    )
    trainingRuns: list[BqmlTrainingRun] | None = None


class BigtableColumnFamily(Resource):
    onlyReadLatest: bool | None = None
    type: str | None = None
    encoding: str | None = None
    protoConfig: BigtableProtoConfig | None = None
    columns: list[BigtableColumn] | None = None
    familyId: str | None = None


class TableRow(Resource):
    f: list[TableCell] | None = None


class TableDataInsertAllResponseInsertErrorsItem(Resource):
    errors: list[ErrorProto] | None = None
    index: int | None = None


class TableDataInsertAllResponse(Resource):
    kind: str | None = "bigquery#tableDataInsertAllResponse"
    insertErrors: list[TableDataInsertAllResponseInsertErrorsItem] | None = None


class RoutineBuildStatus(Resource):
    buildDuration: str | None = None
    buildState: str | None = None
    errorResult: ErrorProto | None = None
    buildStateUpdateTime: str | None = None
    imageSizeBytes: constr(pattern=r"^-?[0-9]+$") | None = None


class MaterializedView(Resource):
    estimatedBytesSaved: constr(pattern=r"^-?[0-9]+$") | None = None
    tableReference: TableReference | None = None
    rejectedReason: str | None = None
    chosen: bool | None = None


class IndexPruningStats(Resource):
    postIndexPruningParallelInputCount: constr(pattern=r"^-?[0-9]+$") | None = None
    baseTable: TableReference | None = None
    indexId: str | None = None
    preIndexPruningParallelInputCount: constr(pattern=r"^-?[0-9]+$") | None = None


class TableReplicationInfo(Resource):
    replicationIntervalMs: constr(pattern=r"^-?[0-9]+$") | None = None
    replicationError: ErrorProto | None = None
    replicatedSourceLastRefreshTime: constr(pattern=r"^-?[0-9]+$") | None = None
    replicationStatus: str | None = None
    sourceTable: TableReference | None = None


class GetIamPolicyRequest(Resource):
    options: GetPolicyOptions | None = None


class StoredColumnsUsage(Resource):
    isQueryAccelerated: bool | None = None
    baseTable: TableReference | None = None
    storedColumnsUnusedReasons: list[StoredColumnsUnusedReason] | None = None


class PartitioningDefinition(Resource):
    partitionedColumn: list[PartitionedColumn] | None = None


class AuditConfig(Resource):
    auditLogConfigs: list[AuditLogConfig] | None = None
    service: str | None = None


class FeatureValue(Resource):
    categoricalValue: CategoricalValue | None = None
    featureColumn: str | None = None
    numericalValue: float | None = None


class SnapshotDefinition(Resource):
    baseTableReference: TableReference | None = None
    snapshotTime: str | None = None


class ArimaResult(Resource):
    arimaModelInfo: list[ArimaModelInfo] | None = None
    seasonalPeriods: list[str] | None = None


class ArimaForecastingMetrics(Resource):
    timeSeriesId: list[str] | None = Field(None, deprecated=True)
    arimaFittingMetrics: list[ArimaFittingMetrics] | None = Field(None, deprecated=True)
    hasDrift: list[bool] | None = Field(None, deprecated=True)
    nonSeasonalOrder: list[ArimaOrder] | None = Field(None, deprecated=True)
    arimaSingleModelForecastingMetrics: (
        list[ArimaSingleModelForecastingMetrics] | None
    ) = None
    seasonalPeriods: list[str] | None = Field(None, deprecated=True)


class VectorSearchStatistics(Resource):
    indexUsageMode: str | None = None
    storedColumnsUsages: list[StoredColumnsUsage] | None = None
    indexUnusedReasons: list[IndexUnusedReason] | None = None


class TableDataList(Resource):
    totalRows: constr(pattern=r"^-?[0-9]+$") | None = None
    pageToken: str | None = None
    etag: str | None = None
    kind: str | None = "bigquery#tableDataList"
    rows: list[TableRow] | None = None


class MaterializedViewStatistics(Resource):
    materializedView: list[MaterializedView] | None = None


class TableChangeInsight(Resource):
    tableReference: TableReference | None = None
    metadataCacheNotUsedButUsedPreviously: bool | None = None
    metadataCacheStalenessInsight: MetadataCacheStalenessInsight | None = None


class TableSchema(Resource):
    fields: list[TableFieldSchema] | None = None
    foreignTypeInfo: ForeignTypeInfo | None = None


class StagePerformanceStandaloneInsight(Resource):
    highCardinalityJoins: list[HighCardinalityJoin] | None = None
    slotContention: bool | None = None
    insufficientShuffleQuota: bool | None = None
    biEngineReasons: list[BiEngineReason] | None = None
    partitionSkew: PartitionSkew | None = None
    stageId: constr(pattern=r"^-?[0-9]+$") | None = None


class SearchStatistics(Resource):
    indexPruningStats: list[IndexPruningStats] | None = None
    indexUsageMode: str | None = None
    indexUnusedReasons: list[IndexUnusedReason] | None = None


class Cluster(Resource):
    centroidId: constr(pattern=r"^-?[0-9]+$") | None = None
    count: constr(pattern=r"^-?[0-9]+$") | None = None
    featureValues: list[FeatureValue] | None = None


class GetQueryResultsResponse(Resource):
    jobComplete: bool | None = None
    jobReference: JobReference | None = None
    numDmlAffectedRows: constr(pattern=r"^-?[0-9]+$") | None = None
    totalRows: constr(pattern=r"^[0-9]+$") | None = None
    errors: list[ErrorProto] | None = None
    rows: list[TableRow] | None = None
    schema_: TableSchema | None = Field(None, alias="schema")
    cacheHit: bool | None = None
    pageToken: str | None = None
    etag: str | None = None
    kind: str | None = "bigquery#getQueryResultsResponse"
    totalBytesProcessed: constr(pattern=r"^-?[0-9]+$") | None = None


class HparamSearchSpaces(Resource):
    colsampleBylevel: DoubleHparamSearchSpace | None = None
    walsAlpha: DoubleHparamSearchSpace | None = None
    numParallelTree: IntHparamSearchSpace | None = None
    batchSize: IntHparamSearchSpace | None = None
    boosterType: StringHparamSearchSpace | None = None
    optimizer: StringHparamSearchSpace | None = None
    dartNormalizeType: StringHparamSearchSpace | None = None
    hiddenUnits: IntArrayHparamSearchSpace | None = None
    numFactors: IntHparamSearchSpace | None = None
    l1Reg: DoubleHparamSearchSpace | None = None
    learnRate: DoubleHparamSearchSpace | None = None
    colsampleBytree: DoubleHparamSearchSpace | None = None
    l2Reg: DoubleHparamSearchSpace | None = None
    activationFn: StringHparamSearchSpace | None = None
    numClusters: IntHparamSearchSpace | None = None
    treeMethod: StringHparamSearchSpace | None = None
    dropout: DoubleHparamSearchSpace | None = None
    minTreeChildWeight: IntHparamSearchSpace | None = None
    maxTreeDepth: IntHparamSearchSpace | None = None
    colsampleBynode: DoubleHparamSearchSpace | None = None
    minSplitLoss: DoubleHparamSearchSpace | None = None
    subsample: DoubleHparamSearchSpace | None = None


class ViewDefinition(Resource):
    foreignDefinitions: list[ForeignViewDefinition] | None = None
    query: str | None = None
    useExplicitColumnNames: bool | None = None
    useLegacySql: bool | None = None
    privacyPolicy: PrivacyPolicy | None = None
    userDefinedFunctionResources: list[UserDefinedFunctionResource] | None = None


class Policy(Resource):
    bindings: list[Binding] | None = None
    auditConfigs: list[AuditConfig] | None = None
    etag: str | None = None
    version: int | None = None


class ConfusionMatrix(Resource):
    rows: list[Row] | None = None
    confidenceThreshold: float | None = None


class IterationResult(Resource):
    trainingLoss: float | None = None
    arimaResult: ArimaResult | None = None
    durationMs: constr(pattern=r"^-?[0-9]+$") | None = None
    principalComponentInfos: list[PrincipalComponentInfo] | None = None
    clusterInfos: list[ClusterInfo] | None = None
    index: int | None = None
    evalLoss: float | None = None
    learnRate: float | None = None


class TableListTablesItemView(Resource):
    useLegacySql: bool | None = None
    privacyPolicy: PrivacyPolicy | None = None


class TableListTablesItem(Resource):
    rangePartitioning: RangePartitioning | None = None
    expirationTime: constr(pattern=r"^-?[0-9]+$") | None = None
    id: str | None = None
    labels: dict[str, str | None] | None = None
    friendlyName: str | None = None
    clustering: Clustering | None = None
    type: str | None = None
    kind: str | None = None
    timePartitioning: TimePartitioning | None = None
    creationTime: constr(pattern=r"^-?[0-9]+$") | None = None
    requirePartitionFilter: bool | None = None
    view: TableListTablesItemView | None = Field(None, title="TableListTablesItemView")
    tableReference: TableReference | None = None


class TableList(Resource):
    totalItems: int | None = None
    kind: str | None = "bigquery#tableList"
    etag: str | None = None
    nextPageToken: str | None = None
    tables: list[TableListTablesItem] | None = None


class ClusteringMetrics(Resource):
    daviesBouldinIndex: float | None = None
    clusters: list[Cluster] | None = None
    meanSquaredDistance: float | None = None


class BigtableOptions(Resource):
    ignoreUnspecifiedColumnFamilies: bool | None = None
    readRowkeyAsString: bool | None = None
    outputColumnFamiliesAsJson: bool | None = None
    columnFamilies: list[BigtableColumnFamily] | None = None


class QueryResponse(Resource):
    location: str | None = None
    cacheHit: bool | None = None
    pageToken: str | None = None
    totalBytesBilled: constr(pattern=r"^-?[0-9]+$") | None = None
    statementType: str | None = None
    queryId: str | None = None
    rows: list[TableRow] | None = None
    schema_: TableSchema | None = Field(None, alias="schema")
    errors: list[ErrorProto] | None = None
    dmlStats: DmlStatistics | None = None
    arrowRecordBatch: ArrowRecordBatch | None = None
    kind: str | None = "bigquery#queryResponse"
    totalSlotMs: constr(pattern=r"^-?[0-9]+$") | None = None
    endTime: constr(pattern=r"^-?[0-9]+$") | None = None
    jobComplete: bool | None = None
    jobReference: JobReference | None = None
    sessionInfo: SessionInfo | None = None
    startTime: constr(pattern=r"^-?[0-9]+$") | None = None
    jobCreationReason: JobCreationReason | None = None
    numDmlAffectedRows: constr(pattern=r"^-?[0-9]+$") | None = None
    creationTime: constr(pattern=r"^-?[0-9]+$") | None = None
    totalRows: constr(pattern=r"^[0-9]+$") | None = None
    pageRowCount: constr(pattern=r"^-?[0-9]+$") | None = None
    totalBytesProcessed: constr(pattern=r"^-?[0-9]+$") | None = None
    arrowSchema: ArrowSchema | None = None


class ExternalDataConfiguration(Resource):
    dateFormat: str | None = None
    objectMetadata: str | None = None
    jsonExtension: str | None = None
    avroOptions: AvroOptions | None = None
    schema_: TableSchema | None = Field(None, alias="schema")
    sourceFormat: str | None = None
    googleSheetsOptions: GoogleSheetsOptions | None = None
    maxBadRecords: int | None = None
    fileSetSpecType: str | None = None
    timestampTargetPrecision: list[int] | None = None
    decimalTargetTypes: list[str] | None = None
    compression: str | None = None
    connectionId: str | None = None
    timestampFormat: str | None = None
    autodetect: bool | None = None
    csvOptions: CsvOptions | None = None
    datetimeFormat: str | None = None
    referenceFileSchemaUri: str | None = None
    bigtableOptions: BigtableOptions | None = None
    ignoreUnknownValues: bool | None = None
    timeZone: str | None = None
    hivePartitioningOptions: HivePartitioningOptions | None = None
    jsonOptions: JsonOptions | None = None
    timeFormat: str | None = None
    parquetOptions: ParquetOptions | None = None
    sourceUris: list[str] | None = None
    metadataCacheMode: str | None = None


class PerformanceInsights(Resource):
    stagePerformanceChangeInsights: list[StagePerformanceChangeInsight] | None = None
    stagePerformanceStandaloneInsights: (
        list[StagePerformanceStandaloneInsight] | None
    ) = None
    avgPreviousExecutionMs: constr(pattern=r"^-?[0-9]+$") | None = None
    tableChangeInsights: list[TableChangeInsight] | None = None


class JobConfigurationLoad(Resource):
    columnNameCharacterMap: str | None = None
    parquetOptions: ParquetOptions | None = None
    allowJaggedRows: bool | None = None
    useAvroLogicalTypes: bool | None = None
    hivePartitioningOptions: HivePartitioningOptions | None = None
    allowQuotedNewlines: bool | None = None
    skipLeadingRows: int | None = None
    timeFormat: str | None = None
    createDisposition: str | None = None
    sourceUris: list[str] | None = None
    encoding: str | None = None
    preserveAsciiControlCharacters: bool | None = None
    rangePartitioning: RangePartitioning | None = None
    schemaInlineFormat: str | None = None
    referenceFileSchemaUri: str | None = None
    copyFilesOnly: bool | None = None
    quote: str | None = None
    createSession: bool | None = None
    timeZone: str | None = None
    ignoreUnknownValues: bool | None = None
    projectionFields: list[str] | None = None
    timestampFormat: str | None = None
    timePartitioning: TimePartitioning | None = None
    decimalTargetTypes: list[str] | None = None
    destinationEncryptionConfiguration: EncryptionConfiguration | None = None
    writeDisposition: str | None = None
    datetimeFormat: str | None = None
    destinationTableProperties: DestinationTableProperties | None = None
    autodetect: bool | None = None
    connectionProperties: list[ConnectionProperty] | None = None
    fieldDelimiter: str | None = None
    sourceColumnMatch: str | None = None
    schemaUpdateOptions: list[str] | None = None
    nullMarkers: list[str] | None = None
    schemaInline: str | None = None
    dateFormat: str | None = None
    nullMarker: str | None = None
    jsonExtension: str | None = None
    maxBadRecords: int | None = None
    destinationTable: TableReference | None = None
    timestampTargetPrecision: list[int] | None = None
    clustering: Clustering | None = None
    fileSetSpecType: str | None = None
    schema_: TableSchema | None = Field(None, alias="schema")
    sourceFormat: str | None = None


class SetIamPolicyRequest(Resource):
    policy: Policy | None = None
    updateMask: str | None = None


class MultiClassClassificationMetrics(Resource):
    confusionMatrixList: list[ConfusionMatrix] | None = None
    aggregateClassificationMetrics: AggregateClassificationMetrics | None = None


class EvaluationMetrics(Resource):
    multiClassClassificationMetrics: MultiClassClassificationMetrics | None = None
    arimaForecastingMetrics: ArimaForecastingMetrics | None = None
    rankingMetrics: RankingMetrics | None = None
    dimensionalityReductionMetrics: DimensionalityReductionMetrics | None = None
    binaryClassificationMetrics: BinaryClassificationMetrics | None = None
    regressionMetrics: RegressionMetrics | None = None
    clusteringMetrics: ClusteringMetrics | None = None


class Table(Resource):
    labels: dict[str, str | None] | None = None
    kind: str | None = "bigquery#table"
    lastModifiedTime: constr(pattern=r"^[0-9]+$") | None = None
    numLongTermPhysicalBytes: constr(pattern=r"^-?[0-9]+$") | None = None
    managedTableType: str | None = None
    numTotalPhysicalBytes: constr(pattern=r"^-?[0-9]+$") | None = None
    numActivePhysicalBytes: constr(pattern=r"^-?[0-9]+$") | None = None
    numLongTermBytes: constr(pattern=r"^-?[0-9]+$") | None = None
    tableReference: TableReference | None = None
    timePartitioning: TimePartitioning | None = None
    numPartitions: constr(pattern=r"^-?[0-9]+$") | None = None
    numRows: constr(pattern=r"^[0-9]+$") | None = None
    numTimeTravelPhysicalBytes: constr(pattern=r"^-?[0-9]+$") | None = None
    defaultRoundingMode: str | None = None
    encryptionConfiguration: EncryptionConfiguration | None = None
    externalDataConfiguration: ExternalDataConfiguration | None = None
    externalCatalogTableOptions: ExternalCatalogTableOptions | None = None
    model: ModelDefinition | None = None
    cloneDefinition: CloneDefinition | None = None
    requirePartitionFilter: bool | None = None
    creationTime: constr(pattern=r"^-?[0-9]+$") | None = None
    restrictions: RestrictionConfig | None = None
    numActiveLogicalBytes: constr(pattern=r"^-?[0-9]+$") | None = None
    schema_: TableSchema | None = Field(None, alias="schema")
    materializedViewStatus: MaterializedViewStatus | None = None
    snapshotDefinition: SnapshotDefinition | None = None
    clustering: Clustering | None = None
    friendlyName: str | None = None
    numBytes: constr(pattern=r"^-?[0-9]+$") | None = None
    tableConstraints: TableConstraints | None = None
    expirationTime: constr(pattern=r"^-?[0-9]+$") | None = None
    selfLink: str | None = None
    location: str | None = None
    maxStaleness: str | None = None
    biglakeConfiguration: BigLakeConfiguration | None = None
    defaultCollation: str | None = None
    id: str | None = None
    partitionDefinition: PartitioningDefinition | None = None
    type: str | None = None
    description: str | None = None
    numPhysicalBytes: constr(pattern=r"^-?[0-9]+$") | None = None
    numCurrentPhysicalBytes: constr(pattern=r"^-?[0-9]+$") | None = None
    rangePartitioning: RangePartitioning | None = None
    numTotalLogicalBytes: constr(pattern=r"^-?[0-9]+$") | None = None
    replicas: list[TableReference] | None = None
    view: ViewDefinition | None = None
    etag: str | None = None
    streamingBuffer: Streamingbuffer | None = None
    materializedView: MaterializedViewDefinition | None = None
    numLongTermLogicalBytes: constr(pattern=r"^-?[0-9]+$") | None = None
    tableReplicationInfo: TableReplicationInfo | None = None
    resourceTags: dict[str, str | None] | None = None


class HparamTuningTrial(Resource):
    hparams: TrainingOptions | None = None
    evalLoss: float | None = None
    endTimeMs: constr(pattern=r"^-?[0-9]+$") | None = None
    startTimeMs: constr(pattern=r"^-?[0-9]+$") | None = None
    evaluationMetrics: EvaluationMetrics | None = None
    status: str | None = None
    errorMessage: str | None = None
    trainingLoss: float | None = None
    trialId: constr(pattern=r"^-?[0-9]+$") | None = None
    hparamTuningEvaluationMetrics: EvaluationMetrics | None = None


class TrainingRun(Resource):
    classLevelGlobalExplanations: list[GlobalExplanation] | None = None
    evaluationMetrics: EvaluationMetrics | None = None
    modelLevelGlobalExplanation: GlobalExplanation | None = None
    dataSplitResult: DataSplitResult | None = None
    trainingOptions: TrainingOptions | None = None
    vertexAiModelId: str | None = None
    trainingStartTime: constr(pattern=r"^-?[0-9]+$") | None = Field(
        None, deprecated=True
    )
    results: list[IterationResult] | None = None
    startTime: str | None = None
    vertexAiModelVersion: str | None = None


class MlStatistics(Resource):
    trainingType: str | None = None
    maxIterations: constr(pattern=r"^-?[0-9]+$") | None = None
    hparamTrials: list[HparamTuningTrial] | None = None
    iterationResults: list[IterationResult] | None = None
    modelType: str | None = None


class JobConfigurationQuery(Resource):
    allowLargeResults: bool | None = None
    defaultDataset: DatasetReference | None = None
    queryParameters: list[QueryParameter] | None = None
    writeIncrementalResults: bool | None = None
    rangePartitioning: RangePartitioning | None = None
    priority: str | None = None
    createSession: bool | None = None
    scriptOptions: ScriptOptions | None = None
    continuous: bool | None = None
    maximumBillingTier: int | None = None
    flattenResults: bool | None = None
    tableDefinitions: dict[str, ExternalDataConfiguration] | None = None
    createDisposition: str | None = None
    userDefinedFunctionResources: list[UserDefinedFunctionResource] | None = None
    schemaUpdateOptions: list[str] | None = None
    maximumBytesBilled: constr(pattern=r"^-?[0-9]+$") | None = None
    useQueryCache: bool | None = None
    clustering: Clustering | None = None
    parameterMode: str | None = None
    preserveNulls: bool | None = None
    destinationTable: TableReference | None = None
    query: str | None = None
    destinationEncryptionConfiguration: EncryptionConfiguration | None = None
    writeDisposition: str | None = None
    useLegacySql: bool | None = None
    timePartitioning: TimePartitioning | None = None
    systemVariables: SystemVariables | None = None
    connectionProperties: list[ConnectionProperty] | None = None


class StandardSqlStructType(Resource):
    fields: list[StandardSqlField] | None = None


class StandardSqlDataType(Resource):
    rangeElementType: StandardSqlDataType | None = None
    structType: StandardSqlStructType | None = None
    arrayElementType: StandardSqlDataType | None = None
    typeKind: str | None = None


class JobStatistics(Resource):
    scriptStatistics: ScriptStatistics | None = None
    sessionInfo: SessionInfo | None = None
    edition: str | None = None
    extract: JobStatistics4 | None = None
    startTime: constr(pattern=r"^-?[0-9]+$") | None = None
    numChildJobs: constr(pattern=r"^-?[0-9]+$") | None = None
    transactionInfo: TransactionInfo | None = None
    creationTime: constr(pattern=r"^-?[0-9]+$") | None = None
    load: JobStatistics3 | None = None
    totalBytesProcessed: constr(pattern=r"^-?[0-9]+$") | None = None
    parentGlobalQueryJob: JobReference | None = None
    quotaDeferments: list[str] | None = None
    globalQueryRemoteRegions: list[str] | None = None
    reservationGroupPath: list[str] | None = None
    completionRatio: float | None = None
    finalExecutionDurationMs: constr(pattern=r"^-?[0-9]+$") | None = None
    reservationUsage: list[JobStatisticsReservationUsageItem] | None = Field(
        None, deprecated=True
    )
    copy_: JobStatistics5 | None = Field(None, alias="copy")
    reservation_id: str | None = None
    dataMaskingStatistics: DataMaskingStatistics | None = None
    parentJobId: str | None = None
    query: JobStatistics2 | None = None
    totalSlotMs: constr(pattern=r"^-?[0-9]+$") | None = None
    rowLevelSecurityStatistics: RowLevelSecurityStatistics | None = None
    endTime: constr(pattern=r"^-?[0-9]+$") | None = None


class Routine(Resource):
    buildStatus: RoutineBuildStatus | None = None
    lastModifiedTime: constr(pattern=r"^-?[0-9]+$") | None = None
    strictMode: bool | None = None
    routineReference: RoutineReference | None = None
    language: str | None = None
    returnType: StandardSqlDataType | None = None
    arguments: list[Argument] | None = None
    description: str | None = None
    pythonOptions: PythonOptions | None = None
    etag: str | None = None
    determinismLevel: str | None = None
    externalRuntimeOptions: ExternalRuntimeOptions | None = None
    importedLibraries: list[str] | None = None
    remoteFunctionOptions: RemoteFunctionOptions | None = None
    sparkOptions: SparkOptions | None = None
    creationTime: constr(pattern=r"^-?[0-9]+$") | None = None
    securityMode: str | None = None
    routineType: str | None = None
    dataGovernanceType: str | None = None
    returnTableType: StandardSqlTableType | None = None
    definitionBody: str | None = None


class JobListJobsItem(Resource):
    kind: str | None = None
    configuration: JobConfiguration | None = None
    principal_subject: str | None = None
    id: str | None = None
    user_email: str | None = None
    statistics: JobStatistics | None = None
    state: str | None = None
    jobReference: JobReference | None = None
    errorResult: ErrorProto | None = None
    status: JobStatus | None = None


class JobList(Resource):
    unreachable: list[str] | None = None
    kind: str | None = "bigquery#jobList"
    etag: str | None = None
    nextPageToken: str | None = None
    jobs: list[JobListJobsItem] | None = None


class RangeValue(Resource):
    end: QueryParameterValue | None = None
    start: QueryParameterValue | None = None


class QueryParameter(Resource):
    name: str | None = None
    parameterType: QueryParameterType | None = None
    parameterValue: QueryParameterValue | None = None


class JobCancelResponse(Resource):
    kind: str | None = "bigquery#jobCancelResponse"
    job: Job | None = None


class QueryParameterTypeStructTypesItem(Resource):
    type: QueryParameterType | None = None
    name: str | None = None
    description: str | None = None


class QueryParameterType(Resource):
    arrayType: QueryParameterType | None = None
    structTypes: list[QueryParameterTypeStructTypesItem] | None = None
    rangeElementType: QueryParameterType | None = None
    type: str | None = None
    timestampPrecision: constr(pattern=r"^-?[0-9]+$") | None = None


class SystemVariables(Resource):
    types: dict[str, StandardSqlDataType] | None = None
    values: dict[str, Any] | None = None


class Model(Resource):
    creationTime: constr(pattern=r"^-?[0-9]+$") | None = None
    defaultTrialId: constr(pattern=r"^-?[0-9]+$") | None = None
    hparamSearchSpaces: HparamSearchSpaces | None = None
    location: str | None = None
    remoteModelInfo: RemoteModelInfo | None = None
    modelReference: ModelReference | None = None
    encryptionConfiguration: EncryptionConfiguration | None = None
    etag: str | None = None
    featureColumns: list[StandardSqlField] | None = None
    description: str | None = None
    hparamTrials: list[HparamTuningTrial] | None = None
    expirationTime: constr(pattern=r"^-?[0-9]+$") | None = None
    transformColumns: list[TransformColumn] | None = None
    bestTrialId: constr(pattern=r"^-?[0-9]+$") | None = Field(None, deprecated=True)
    modelType: str | None = None
    labels: dict[str, str | None] | None = None
    labelColumns: list[StandardSqlField] | None = None
    trainingRuns: list[TrainingRun] | None = None
    friendlyName: str | None = None
    lastModifiedTime: constr(pattern=r"^-?[0-9]+$") | None = None
    optimalTrialIds: list[constr(pattern=r"^-?[0-9]+$")] | None = None


class TransformColumn(Resource):
    name: str | None = None
    transformSql: str | None = None
    type: StandardSqlDataType | None = None


class Job(Resource):
    jobCreationReason: JobCreationReason | None = None
    jobReference: JobReference | None = None
    status: JobStatus | None = None
    configuration: JobConfiguration | None = None
    etag: str | None = None
    kind: str | None = "bigquery#job"
    id: str | None = None
    user_email: str | None = None
    principal_subject: str | None = None
    selfLink: str | None = None
    statistics: JobStatistics | None = None


class ListModelsResponse(Resource):
    nextPageToken: str | None = None
    models: list[Model] | None = None


class QueryRequest(Resource):
    continuous: bool | None = None
    jobTimeoutMs: constr(pattern=r"^-?[0-9]+$") | None = None
    defaultDataset: DatasetReference | None = None
    queryParameters: list[QueryParameter] | None = None
    writeIncrementalResults: bool | None = None
    maxSlots: int | None = None
    queryResultsFormat: str | None = None
    maxResults: int | None = None
    createSession: bool | None = None
    requestId: str | None = None
    destinationEncryptionConfiguration: EncryptionConfiguration | None = None
    useLegacySql: bool | None = None
    jobCreationMode: str | None = None
    arrowSerializationOptions: ArrowSerializationOptions | None = None
    connectionProperties: list[ConnectionProperty] | None = None
    location: str | None = None
    timeoutMs: int | None = None
    reservation: str | None = None
    dryRun: bool | None = None
    labels: dict[str, str | None] | None = None
    maximumBytesBilled: constr(pattern=r"^-?[0-9]+$") | None = None
    kind: str | None = "bigquery#queryRequest"
    useQueryCache: bool | None = None
    formatOptions: DataFormatOptions | None = None
    parameterMode: str | None = None
    preserveNulls: bool | None = Field(None, deprecated=True)
    query: str | None = None


class ListRoutinesResponse(Resource):
    nextPageToken: str | None = None
    routines: list[Routine] | None = None


class Argument(Resource):
    dataType: StandardSqlDataType | None = None
    argumentKind: str | None = None
    tableType: StandardSqlTableType | None = None
    mode: str | None = None
    name: str | None = None
    isAggregate: bool | None = None


class JobConfiguration(Resource):
    maxSlots: int | None = None
    dryRun: bool | None = None
    labels: dict[str, str | None] | None = None
    load: JobConfigurationLoad | None = None
    jobType: str | None = None
    extract: JobConfigurationExtract | None = None
    jobTimeoutMs: constr(pattern=r"^-?[0-9]+$") | None = None
    query: JobConfigurationQuery | None = None
    copy_: JobConfigurationTableCopy | None = Field(None, alias="copy")
    reservation: str | None = None


class JobStatistics2(Resource):
    totalBytesBilled: constr(pattern=r"^-?[0-9]+$") | None = None
    totalServicesSkuSlotMs: constr(pattern=r"^-?[0-9]+$") | None = None
    statementType: str | None = None
    reservationUsage: list[JobStatistics2ReservationUsageItem] | None = Field(
        None, deprecated=True
    )
    exportDataStatistics: ExportDataStatistics | None = None
    ddlAffectedRowAccessPolicyCount: constr(pattern=r"^-?[0-9]+$") | None = None
    cacheHit: bool | None = None
    ddlTargetDataset: DatasetReference | None = None
    transferredBytes: constr(pattern=r"^-?[0-9]+$") | None = None
    undeclaredQueryParameters: list[QueryParameter] | None = None
    genAiStats: GenAiStats | None = None
    queryPlan: list[ExplainQueryStage] | None = None
    schema_: TableSchema | None = Field(None, alias="schema")
    vectorSearchStatistics: VectorSearchStatistics | None = None
    dclTargetDataset: DatasetReference | None = None
    billingTier: int | None = None
    metadataCacheStatistics: MetadataCacheStatistics | None = None
    ddlTargetRowAccessPolicy: RowAccessPolicyReference | None = None
    ddlDestinationTable: TableReference | None = None
    searchStatistics: SearchStatistics | None = None
    queryInfo: QueryInfo | None = None
    estimatedBytesProcessed: constr(pattern=r"^-?[0-9]+$") | None = None
    biEngineStatistics: BiEngineStatistics | None = None
    totalPartitionsProcessed: constr(pattern=r"^-?[0-9]+$") | None = None
    dclTargetTable: TableReference | None = None
    mlStatistics: MlStatistics | None = None
    referencedPropertyGraphs: list[PropertyGraphReference] | None = None
    referencedTables: list[TableReference] | None = None
    materializedViewStatistics: MaterializedViewStatistics | None = None
    modelTraining: BigQueryModelTraining | None = None
    loadQueryStatistics: LoadQueryStatistics | None = None
    sparkStatistics: SparkStatistics | None = None
    modelTrainingCurrentIteration: int | None = None
    dmlStats: DmlStatistics | None = None
    totalSlotMs: constr(pattern=r"^-?[0-9]+$") | None = None
    ddlTargetRoutine: RoutineReference | None = None
    ddlTargetTable: TableReference | None = None
    numDmlAffectedRows: constr(pattern=r"^-?[0-9]+$") | None = None
    incrementalResultStats: IncrementalResultStats | None = None
    referencedRoutines: list[RoutineReference] | None = None
    totalBytesProcessedAccuracy: str | None = None
    performanceInsights: PerformanceInsights | None = None
    timeline: list[QueryTimelineSample] | None = None
    modelTrainingExpectedTotalIteration: constr(pattern=r"^-?[0-9]+$") | None = None
    objectStorageStats: list[ObjectStorageStats] | None = None
    dclTargetView: TableReference | None = None
    externalServiceCosts: list[ExternalServiceCost] | None = None
    totalBytesProcessed: constr(pattern=r"^-?[0-9]+$") | None = None
    ddlOperationPerformed: str | None = None


class StandardSqlField(Resource):
    type: StandardSqlDataType | None = None
    name: str | None = None


class StandardSqlTableType(Resource):
    columns: list[StandardSqlField] | None = None


class QueryParameterValue(Resource):
    structValues: dict[str, QueryParameterValue] | None = None
    rangeValue: RangeValue | None = None
    value: str | None = None
    arrayValues: list[QueryParameterValue] | None = None


TableFieldSchema.model_rebuild()
JobConfigurationQuery.model_rebuild()
StandardSqlStructType.model_rebuild()
JobStatistics.model_rebuild()
Routine.model_rebuild()
JobListJobsItem.model_rebuild()
RangeValue.model_rebuild()
QueryParameter.model_rebuild()
JobCancelResponse.model_rebuild()
QueryParameterTypeStructTypesItem.model_rebuild()
Model.model_rebuild()
Job.model_rebuild()
Argument.model_rebuild()
