volumes:
  bigquery_data: {}
services:
  bigquery:
    image: ghcr.io/novucs/local-bigquery:0.2.3
    ports:
      - "9050:9050"
    environment:
      # Optional configuration, defaults are shown
      BIGQUERY_PORT: 9050
      BIGQUERY_HOST: 0.0.0.0
      DATA_DIR: /data
      DEFAULT_PROJECT_ID: local
      DEFAULT_DATASET_ID: local
      INTERNAL_PROJECT_ID: internal
      INTERNAL_DATASET_ID: internal
      # Support for external connections to Postgres, requires an available Postgres instance.
      # SELECT * FROM EXTERNAL_QUERY('us.default', 'SELECT 1');
      POSTGRES_CONNECTION_ID: us.default
      POSTGRES_URI: postgresql://postgres:example@db:5432/postgres
    volumes:
      - bigquery_data:/data
