import json
import pathlib
import subprocess
import sys
import tempfile
import urllib.request

DISCOVERY_URL = "https://bigquery.googleapis.com/discovery/v1/apis/bigquery/v2/rest"
IGNORED_KEYS = {
    "description",
    "enum",
    "enumDescriptions",
    "enumDeprecated",
    "format",
    "id",
    "pattern",
}
CODEGEN_OPTIONS = """
    --input-file-type jsonschema
    --output-model-type pydantic_v2.BaseModel
    --target-python-version 3.13
    --class-name Discovery
    --use-title-as-name
    --use-standard-collections
    --use-union-operator
    --base-class local_bigquery.resource.Resource
    --formatters ruff-format
"""
PACKAGE = pathlib.Path(__file__).parent.parent / "src" / "local_bigquery"


def to_json_schema(node, name: str, key: str = ""):
    if not isinstance(node, dict):
        return node
    ignored = IGNORED_KEYS if key == "kind" else IGNORED_KEYS | {"default"}
    node = {k: v for k, v in node.items() if k not in ignored}
    if "$ref" in node:
        return {"$ref": f"#/$defs/{node['$ref']}"}
    if "properties" in node:
        node["title"] = name
        node["properties"] = {
            key: to_json_schema(value, name + key[0].upper() + key[1:], key)
            for key, value in node["properties"].items()
        }
    if "items" in node:
        node["items"] = to_json_schema(node["items"], name + "Item")
    if isinstance(node.get("additionalProperties"), dict):
        node["additionalProperties"] = to_json_schema(
            node["additionalProperties"], name + "Value"
        )
    return node


def main(source: str = DISCOVERY_URL):
    with urllib.request.urlopen(source) if "://" in source else open(source) as f:
        discovery = json.load(f)
    (PACKAGE / "discovery.json").write_text(json.dumps(discovery, indent=1) + "\n")
    schema = {
        "$defs": {
            name: to_json_schema(value, name)
            for name, value in discovery["schemas"].items()
        }
    }
    with tempfile.NamedTemporaryFile("w", suffix=".json") as f:
        json.dump(schema, f)
        f.flush()
        subprocess.run(
            [
                "datamodel-codegen",
                *f"--input {f.name} --output {PACKAGE / 'models.py'}".split(),
                *CODEGEN_OPTIONS.split(),
                "--custom-file-header",
                "# Generated by scripts/generate_models.py. Do not edit.",
            ],
            check=True,
        )


if __name__ == "__main__":
    main(*sys.argv[1:])
